name: Super Lint Code Base

# Documentation:
# https://github.com/github/super-linter

on:
  push:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: true
          FILTER_REGEX_INCLUDE: ".*Assets/Scripts/.*.cs"
